# Generated by Django 4.1.6 on 2023-02-07 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comision', models.IntegerField()),
                ('porc_entrada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgo.broker')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgo.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('investment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgo.investment')),
                ('probability_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgo.probability')),
                ('risk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgo.risk')),
            ],
        ),
    ]
